web/SiameseSearchWeb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('search/', include('search.urls')),
    path('admin/', admin.site.urls),
]

web/search/urls.py
from django.urls import path

from . import views

app_name = "search"
urlpatterns = [
    path('', views.index, name='index'),
    path('question_search/', views.question_search, name="question_search"),
    path('question_search/<int:page>/', views.question_search_pagination, name="question_search_pagination"),
    path('api/question_search/', views.question_search_content_loader, name="question_search_content_loader"),
    path('api/question_search/<int:page>/', views.question_search_content_loader, name="question_search_content_loader"),
    path('explore_questions/', views.explore_questions, name="explore_questions"),
    path('explore_questions/<int:page>/', views.explore_questions_pagination, name="explore_questions_pagination"),
    path('api/explore_questions/', views.explore_questions_content_loader, name="explore_questions_content_loader"),
    path('api/explore_questions/<int:page>/', views.explore_questions_content_loader, name="explore_questions_content_loader"),
    path('detail/<str:page>/<int:post_id>/', views.detail, name="detail"),

]

web/search/models.py
from django.db import models

# Create your models here.

web/search/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponse
from django.template.loader import render_to_string
from elasticsearch_dsl.connections import connections

from data.documents import Post, User, Comment, ES_HOSTS, ES_LOGIN
from data.utils import sanitize_html_for_web
from .search import search

import datetime
import json

POST_PER_PAGE = 15


# Create your views here.
def index(request):
    """
    Index view controller

    :param request: http request object
    :return: rendered page
    """
    return render(request, "search/index.html", None)


def question_search_pagination(request, page):
    """
    Question search with pagination view controller

    :param request: http request object
    :param page: currently selected page
    :return: rendered page
    """
    form = {}
    url_params = request.GET.copy().urlencode()

    # get GET parameters
    search_type = request.GET.get("search_type", None)
    search_text = request.GET.get("search_text", None)

    # define the required search type
    if search_type is None:
        if "search_type" in request.COOKIES:
            search_type = request.COOKIES["search_type"]
        else:
            search_type = "fulltext"

    if search_text is None:
        search_text = ""

    page = page if page > 0 else 1

    # determine filters
    if request.GET.getlist("pages") and request.GET.get("pages", "all") != "all":
        pages = request.GET.getlist("pages")
        form["pages"] = pages

    if request.GET.get("with_answer", None) is not None:
        form["with_answer"] = True

    if request.GET.get("date_range_start", None) and request.GET.get("date_range_end", None):
        date_start_string = request.GET["date_range_start"]
        date_end_string = request.GET["date_range_end"]
        date_start = datetime.datetime.strptime(date_start_string, "%Y-%m-%d")
        date_end = datetime.datetime.strptime(date_end_string, "%Y-%m-%d")
    else:
        date_start = datetime.datetime.now() - datetime.timedelta(days=730)
        date_end = datetime.datetime.now()

    form["date_range_start"] = str(date_start.date())
    form["date_range_end"] = str(date_end.date())

    # pagination settings and feed dict
    pagination_info = {"page_nr": page,
                       "next_page_nr": page + 1,
                       "previous_page_nr": page - 1,
                       "url_params": url_params}

    # render the template
    response = render(request, "search/question_search.html",
                      context={"pagination_info": pagination_info, "display_search": True,
                               "search_text": search_text, "form": form})

    response.set_cookie("search_type", search_type)
    return response


def question_search(request):
    """
    Question search without pagination view controller

    :param request: http request object
    :return: rendered page
    """
    return question_search_pagination(request, 1)


def explore_questions_pagination(request, page):
    """
    Explore question with pagination view controller

    :param request: http request
    :param page: currently selected page
    :return: rendered page
    """
    form = {}
    url_params = request.GET.copy().urlencode()

    # determine which posts should be shown according to selected page
    page = page if page > 0 else 1
    post_start = (page - 1) * POST_PER_PAGE
    post_end = (page * POST_PER_PAGE) + 1

    # determine filters
    if request.GET.getlist("pages") and request.GET.get("pages", "all") != "all":
        pages = request.GET.getlist("pages")
        form["pages"] = pages

    if request.GET.get("with_answer", None) is not None:
        form["with_answer"] = True

    if request.GET.get("date_range_start", None) and request.GET.get("date_range_end", None):
        date_start_string = request.GET["date_range_start"]
        date_end_string = request.GET["date_range_end"]
        date_start = datetime.datetime.strptime(date_start_string, "%Y-%m-%d")
        date_end = datetime.datetime.strptime(date_end_string, "%Y-%m-%d")
    else:
        date_start = datetime.datetime.now() - datetime.timedelta(days=730)
        date_end = datetime.datetime.now()

    form["date_range_start"] = str(date_start.date())
    form["date_range_end"] = str(date_end.date())

    # pagination settings and feed dict
    has_previous = True if page > 1 else False
    has_next = True
    pagination_info = {"has_previous": has_previous, "has_next": has_next, "page_nr": page, "next_page_nr": page + 1,
                       "previous_page_nr": page - 1, "url_params": url_params}

    # render the template
    return render(request, "search/explore_questions.html",
                  context={"pagination_info": pagination_info, "display_search": True, "form": form})


def explore_questions(request):
    """
    Explore question without pagination view controller

    :param request: http request object
    :return: rendered page
    """
    return explore_questions_pagination(request, 1)


def detail(request, post_id, page):
    """
    Post detail view controller

    :param request: http request object
    :param post_id: id for which the detail is displayed
    :param page: page of article
    :return: rendered page
    """
    connections.create_connection(hosts=ES_HOSTS, http_auth=ES_LOGIN)
    post_result = Post.get_post(post_id, page)

    if post_result is None:
        raise Http404

    # get accepted answer for given question and create feed dict for that
    accepted_answer = None
    if post_result.accepted_answer_ID is not None:
        accepted_answer_result = Post.get_post(post_result.accepted_answer_ID, page)
        accepted_answer = {"author": User.get_user_display_name(accepted_answer_result.owner_ID, page),
                           "date": accepted_answer_result.creation_date,
                           "text": sanitize_html_for_web(accepted_answer_result.text),
                           "post_ID": accepted_answer_result.post_ID}

    # create feed dict for template
    post = {"title": post_result.title, "date": post_result.creation_date,
            "text": sanitize_html_for_web(post_result.text),
            "author": User.get_user_display_name(post_result.owner_ID, page)}

    # search for answers and comments for given question
    except_id = accepted_answer['post_ID'] if accepted_answer is not None else None
    answers = Post.get_post_answers_information(post_result.post_ID, page, except_id)
    comments = Comment.get_post_comments_information(post_result.post_ID, page)

    # render the template
    return render(request, 'search/question_details.html', context={"display_search": True,
                                                                    "post": post,
                                                                    "accepted_answer": accepted_answer,
                                                                    "answers": answers,
                                                                    "comments": comments})


def question_search_content_loader(request, page=1):
    """
    Searches for the the posts based on given queries and return selected page of results as a
    JSON objects. It is used by AJAX

    :param request: http request object
    :param page: page of information for pagination
    :return: data dictionary as a JSON object that is the processed by AJAX
    """
    connections.create_connection(hosts=ES_HOSTS, http_auth=ES_LOGIN)

    # get GET parameters
    search_type = request.GET.get("search_type", None)
    search_text = request.GET.get("search_text", None)

    # define the required search type
    if search_type is None:
        if "search_type" in request.COOKIES:
            search_type = request.COOKIES["search_type"]
        else:
            search_type = "fulltext"

    if search_text is None:
        search_text = ""

    page = page if page > 0 else 1

    # determine filters
    if request.GET.get("date_range_start", None) and request.GET.get("date_range_end", None):
        date_start_string = request.GET["date_range_start"]
        date_end_string = request.GET["date_range_end"]
        date_start = datetime.datetime.strptime(date_start_string, "%Y-%m-%d")
        date_end = datetime.datetime.strptime(date_end_string, "%Y-%m-%d")
    else:
        date_start = datetime.datetime.now() - datetime.timedelta(days=730)
        date_end = datetime.datetime.now()

    date_filter = {"start": date_start, "end": date_end}

    # perform search
    posts = search(search_type, search_text, page, POST_PER_PAGE, request, date_filter)

    # pagination settings and feed dict
    has_previous = True if page > 1 else False
    has_next = True if len(posts) > POST_PER_PAGE else False

    # render the template
    html = render_to_string('search/posts_displays.html', {"posts": posts[:-1]})
    json_dict = {"html": html, "has_next_page": has_next, "has_previous_page": has_previous}

    response = HttpResponse(json.dumps(json_dict))
    response.set_cookie("search_type", search_type)
    return response


def explore_questions_content_loader(request, page=1):
    """
    Return selected page of results (from the newest) as a JSON objects. It is used by AJAX.

    :param request: http request object
    :param page: page of information for pagination
    :return: data dictionary as a JSON object that is the processed by AJAX
    """
    # determine which posts should be shown according to selected page
    page = page if page > 0 else 1
    post_start = (page - 1) * POST_PER_PAGE
    post_end = (page * POST_PER_PAGE) + 1

    has_previous_page = True if page > 1 else False

    # search for posts that will be show
    connections.create_connection(hosts=ES_HOSTS, http_auth=ES_LOGIN)
    s = Post.search().filter("term", post_type=1).sort({"creation_date": {"order": "desc"}})[post_start:post_end]

    # determine filters

web/search/templates/search/base.html
<!DOCTYPE html>
<html>

<head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=yes">
    <title>Siamese search</title>
    <meta name="description" content="Type">
    <link rel="stylesheet" href="{% static "search/bootstrap.min.css" %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic">
    <link rel="stylesheet" href="{% static "search/Navigation-with-Button.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static 'search/my_css.css' %}">
    <link rel="stylesheet" type="text/css", href="{% static 'search/Testimonials.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    {% block custom_css %}{% endblock %}
</head>

<body>
<div>
    <nav class="navbar navbar-light navbar-expand-md navigation-clean-button">
        <div class="container"><a class="navbar-brand" href="{% url 'search:index' %}">Siamese search</a>
            <button data-toggle="collapse" class="navbar-toggler" data-target="#navcol-1"><span class="sr-only">Toggle navigation</span><span
                    class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item" role="presentation"></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'search:explore_questions' %}">Explore</a></li>
                </ul>
                {% if display_search %}
                <form class="form-inline my-2 my-lg-0" style="margin-right: 10px" action="{% url 'search:question_search' %}" method="get">
                    <input class="form-control mr-sm-2" type="search" name="search_text" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>
                </form>
                {% endif %}
                <span class="navbar-text actions"> <a class="login" href="#">Admin login</a></span></div>
        </div>
    </nav>
</div>
{% block page_header %}
{% endblock %}
{% block content %}
{% endblock %}
<footer class="footer bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 my-auto h-100 text-center text-lg-left">
                <ul class="list-inline mb-2">
                    <li class="list-inline-item"><a href="#">About</a></li>
                    <li class="list-inline-item"><span>⋅</span></li>
                    <li class="list-inline-item"><a href="#">Contact</a></li>
                    <li class="list-inline-item"><span>⋅</span></li>
                    <li class="list-inline-item"><a href="#">Terms of &nbsp;Use</a></li>
                    <li class="list-inline-item"><span>⋅</span></li>
                    <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
                </ul>
                <p class="text-muted small mb-4 mb-lg-0">© Siamese search 2019. All Rights Reserved.</p>
            </div>
        </div>
    </div>
</footer>
</body>

</html>

web/search/templates/search/explore_questions.html
{% extends 'search/question_display_base.html' %}
{% load static %}
{% block page_header %}
<header class="testimonials-clean" style="background-image: url({% static 'search/images/background.jpg' %});background-size: cover;padding-bottom: 31px;">
    <div class="container">
        <div class="intro">
            <h2 class="text-center">Explore questions</h2>
            <p class="text-center" style="color: rgb(73,76,78);">On this site you can explore old questions from StackExchange sites and filter them using many parameters.</p>
        </div>
    </div>
</header>
{% endblock %}
{% block pagination %}
    <nav class="d-flex d-sm-flex d-md-flex d-lg-flex d-xl-flex justify-content-center justify-content-sm-center justify-content-md-center justify-content-lg-center justify-content-xl-center">
        <ul class="pagination">
            <li class="page-item" id="prev_page_nav" style="display: none"><a class="page-link" href="{% url 'search:explore_questions_pagination' pagination_info.previous_page_nr %}?{{ pagination_info.url_params }}" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
            <li class="page-item" id="current_page_nav" style="display: none"><a class="page-link" href="#">{{ pagination_info.page_nr }}</a></li>
            <li class="page-item" id="next_page_nav" style="display: none"><a class="page-link" href="{% url 'search:explore_questions_pagination' pagination_info.next_page_nr %}?{{ pagination_info.url_params }}" aria-label="Next"><span aria-hidden="true">»</span></a></li>
        </ul>
    </nav>
    <script type="text/javascript">
    window.onload = get_page_content({{ pagination_info.page_nr }})
    function get_page_content(page)
    {
        var pages_list = []
        $.each($("input[name='pages']:checked"), function(){
            pages_list.push($(this).val())
        })
        var request = $.ajax({
            url: "{% url 'search:explore_questions_content_loader' %}"+page+"/",
            type: 'GET',
            data: {date_range_start: $('#date_range_start_input').attr("value"), date_range_end: $("#date_range_end_input").attr("value"), with_answer: $("#with_answer_checkbox").attr("checked"), pages: pages_list}
        });
        request.done(function (data) {
            var obj = JSON.parse(data);
            $("#question_list").html(obj.html);
            $("#current_page_nav").show();
            if(obj.has_next_page)
            {
                $("#next_page_nav").show();
            }

            if(obj.has_previous_page)
            {
                $("#prev_page_nav").show();
            }
        })
    }

</script>
{% endblock %}
{% block filter_form_tag %}
    <form method="get" action="{% url 'search:explore_questions' %}">
{% endblock %}

web/search/templates/search/index.html
{% extends 'search/base.html' %}
{% load static %}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'search/my_css.css' %}">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
{% endblock %}
{% block content %}
<header class="masthead text-white text-center" style="background: url('../../static/search/images/bg-masthead.jpg')no-repeat center center;background-size: cover;background-image: url('{% static "search/images/background.jpg" %}');">
    <div class="overlay"></div>
    <div class="container">
        <form method="get" action="{% url 'search:question_search' %}">
            <div class="row">
                <div class="col-xl-9 mx-auto">
                    <h1 class="mb-5">Search better and faster in thousands of Stack Exchange data!</h1>
                </div>
                <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
                    <div class="form-row">
                        <div class="col-12 col-md-9 mb-2 mb-md-0"><textarea name="search_text" class="form-control"></textarea></div>
                        <div class="col-12 col-md-3">
                            <button class="btn btn-primary btn-block btn-lg" type="submit" style="height: 64px;">
                                Search
                            </button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row" style="margin: 20px;">
                <div class="col" id="fulltext_checkbox_container">
                    <div class="form-check"><input class="form-check-input" type="radio" id="formCheck-1"
                                                   name="search_type" value="fulltext" checked=""><label
                            class="form-check-label" for="formCheck-1">Fulltext search</label></div>
                </div>
                <div class="col" id="siamese_checkbox_container">
                    <div class="form-check"><input class="form-check-input" type="radio" id="formCheck-2"
                                                   name="search_type" value="siamese"><label class="form-check-label"
                                                                                             for="formCheck-2">SiameseSearch</label>
                    </div>
                </div>
            </div>
        </form>
    </div>
</header>
{% endblock %}

web/search/templates/search/posts_displays.html
{% load static %}
{% for post in posts %}
<div class="row shadow-sm post_list_item_container" style="margin-bottom: 15px;">
    <div class="col post_list_item">
        <div class="post_meta">
            <a href="{% url 'search:detail' post.page post.post_ID %}">
                <h5>{{ post.title }}</h5>
            </a>
            <span class="comment_count">
                <a class="comment_count_icon" href="{% url 'search:detail' post.page post.post_ID %}">0</a>
                <p class="d-xl-flex justify-content-xl-start comment_count_nr">{{ post.comment_count }}</p>
            </span>
            <p class="author_name"><i class="fa fa-user"></i>{{ post.author_name }}</p>
            <p class="post_page"><i class="fas fa-book-open"></i> {{ post.page }}</p>
            <p class="post_accepted_answer">Accepted answer:&nbsp;<i class="far {% if post.accepted_answer_ID %} fa-check-circle {% else %} fa-times-circle {% endif %}"></i></p>
        </div>
        <hr class="post_meta_separator">
        <div style="clear: right"></div>
        <div class="post_text_container">
            <p>{{ post.text|safe }}</p>
        </div>
    </div>
</div>
{% empty %}
<div class="alert alert-warning" role="alert" style="margin-left: 10%; margin-right: 10%;" align="center">
    Sorry, there is no post to be displayed!
</div>
{% endfor %}

web/search/templates/search/question_details.html
{% extends 'search/base.html' %}
{% load static %}
{% block page_header %}
    <header class="testimonials-clean" style="background-image: url({% static 'search/images/background.jpg' %});background-size: cover;padding-bottom: 31px;">
        <div class="container">
            <div class="intro">
                <h2 class="text-center">Question details</h2>
                <p class="text-center" style="color: rgb(73,76,78);">On this site you can explore all the content asociated to chosen post.</p>
            </div>
        </div>
    </header>
{% endblock %}
{% block content %}
    <main class="bg-light testimonials-clean" style="background-color: #ecf0f1; padding: 10px">
        <div class="jumbotron shadow" id="article">
            <h1 class="text-center" id="article_title">{{ post.title }}<br></h1>
            <p class="text-center" id="article_author"><i class="fa fa-user" style="margin-right: 10px;"></i>{{ post.author }}</p>
            <p class="text-center" id="article_date"><i class="far fa-calendar-times" style="margin-right: 10px;"></i>{{ post.date }}</p>
            <hr>
            <h6><i class="fa fa-question" style="margin-right: 10px;"></i>Question:</h6>
            <div class="card" id="article_text">
                <div class="card-body">
                    <p class="card-text">{{ post.text|safe }}</p>
                </div>
            </div>
            <hr>
            {% if accepted_answer %}
            <h6><i class="fas fa-comment-dots" style="margin-right: 10px;"></i>Accepted answer:</h6>
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title text-muted" style="margin-bottom: 12px;"><i class="fa fa-user" style="margin-right: 14px;"></i>{{ accepted_answer.author }}</h6>
                    <h6 class="text-muted card-subtitle mb-2"><i class="far fa-calendar-times" style="margin-right: 10px;"></i>{{ accepted_answer.date }}</h6>
                    <p class="card-text">{{ accepted_answer.text|safe }}</p>
                </div>
            </div>
            {% endif %}
            {% if answers %}
            <h6 style="margin-top: 10px;"><i class="far fa-comment-dots" style="margin-right: 10px;"></i>Answers:</h6>
                <div id="answers_scrollbar">
                {% for answer in answers %}
                    <div class="card" style="margin-bottom: 10px;">
                        <div class="card-body">
                            <h6 class="card-title text-muted" style="margin-bottom: 12px;"><i class="fa fa-user" style="margin-right: 14px;"></i>{{ answer.author }}</h6>
                            <h6 class="text-muted card-subtitle mb-2"><i class="far fa-calendar-times" style="margin-right: 10px;"></i>{{ answer.date }}</h6>
                            <p class="card-text">{{ answer.text|safe }}</p>
                        </div>
                    </div>
                {% endfor %}
                </div>
            {% endif %}
            <hr>
            {% if comments %}
            <h6 style="margin-top: 10px;"><i class="far fa-comments" style="margin-right: 10px;"></i>Comments:</h6>
                <div id="comments_scrollbar">
                {% for comment in comments %}
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title text-muted" style="margin-bottom: 12px;"><i class="fa fa-user" style="margin-right: 14px;"></i>{{ comment.author }}</h6>
                            <h6 class="text-muted card-subtitle mb-2"><i class="far fa-calendar-times" style="margin-right: 10px;"></i>{{ comment.date }}</h6>
                            <p class="card-text">{{ comment.text|safe }}.</p>
                        </div>
                    </div>
                {% endfor%}
                </div>
            {% endif %}
        </div>
    </main>
{% endblock %}

web/search/templates/search/question_search.html
{% extends 'search/question_display_base.html' %}
{% load static %}
{% block page_header %}
<header class="testimonials-clean" style="background-image: url({% static 'search/images/background.jpg' %});background-size: cover;padding-bottom: 31px;">
    <div class="container">
        <div class="intro">
            <h2 class="text-center">Search questions</h2>
            <p class="text-center" style="color: rgb(73,76,78);">On this site you can see results of your search sorted from the best to the worst match.</p>
        </div>
    </div>
</header>
{% endblock %}
{% block pagination %}
    <nav class="d-flex d-sm-flex d-md-flex d-lg-flex d-xl-flex justify-content-center justify-content-sm-center justify-content-md-center justify-content-lg-center justify-content-xl-center">
        <ul class="pagination">
            <li class="page-item" id="prev_page_nav" style="display: none"><a class="page-link" href="{% url 'search:question_search_pagination' pagination_info.previous_page_nr %}?{{ pagination_info.url_params }}" aria-label="Previous"><span aria-hidden="true">«</span></a></li>
            <li class="page-item" id="current_page_nav" style="display: none"><a class="page-link" href="#">{{ pagination_info.page_nr }}</a></li>
            <li class="page-item" id="next_page_nav" style="display: none"><a class="page-link" href="{% url 'search:question_search_pagination' pagination_info.next_page_nr %}?{{ pagination_info.url_params }}" aria-label="Next"><span aria-hidden="true">»</span></a></li>
        </ul>
    </nav>
    <script type="text/javascript">
    window.onload = get_page_content({{ pagination_info.page_nr }})
    function get_page_content(page)
    {
        var pages_list = []
        $.each($("input[name='pages']:checked"), function(){
            pages_list.push($(this).val())
        })
        var request = $.ajax({
            url: "{% url 'search:question_search_content_loader' %}"+page+"/",
            type: 'GET',
            data: { date_range_start: $('#date_range_start_input').attr("value"),
                    date_range_end: $("#date_range_end_input").attr("value"),
                    with_answer: $("#with_answer_checkbox").attr("checked"),
                    pages: pages_list,
                    search_text: $("#search_text_input").attr("value")}
        });
        request.done(function (data) {
            var obj = JSON.parse(data);
            $("#question_list").html(obj.html);
            $("#current_page_nav").show();
            if(obj.has_next_page)
            {
                $("#next_page_nav").show();
            }

            if(obj.has_previous_page)
            {
                $("#prev_page_nav").show();
            }
        })
    }

</script>
{% endblock %}
{% block filter_form_tag %}
    <form method="get" action="{% url 'search:question_search' %}">
    <input type="hidden" name="search_text" value="{{ search_text }}" id="search_text_input">
{% endblock %}